### ISSUE TITLE
Why not Formik instead?

### ISSUE THREAD

**Issue by bettiolo** [tes/rolling-fields#5]
See: https://github.com/jaredpalmer/formik

**Comment by rachelcdavies** [comment]
We are using this **with** Formik in app-marketing-ui

**Comment by bettiolo** [comment]
Can you explain better?

**Comment by sithmel** [comment]
Formik is a library to help managing forms.
This is a form fields generator. It allows you to build a form based on a schema.

There are alternatives around, but they are quite inflexible. This is highly customizable and can be integrated with other libraries such as Formik, redux form etc.

**Comment by rachelcdavies** [comment]
that's the point of the hack to explain this better in both the readme and a blog post. Basically rolling fields is for creating a form based on data and this can be wrapped in a Formik form as we already do in app-marketing-ui. As this repo is public, I can't just add links to our internal Tes usage of it. Hence the idea of a better readme and blog post with generic not Tes specific examples.

**Comment by bettiolo** [comment]
Formik has a JSX schema AFAIK? rolling-form is translating a javascript definition to a JSX definition like https://github.com/jaredpalmer/formik/blob/master/examples/Basic.js? I am genuinely trying to understand why a Javascript definition is better than a JSX definition (as you would need to specify jsx in both except for trivial use cases)?

**Comment by sithmel** [comment]
@bettiolo ok, I understand the confusion.
We need for our project to store the form schema in a database. So it has to be serializable.

**Comment by rachelcdavies** [comment]
@bettiolo I've updated the project readme to better explain the purpose of this project and benefits on top of Formik. Let me know if it is clear enough to close this issue.
